resource_registry:
  OS::TripleO::Compute::Net::SoftwareConfig: ./nic-configs/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: ./nic-configs/controller.yaml

parameter_defaults:
  # NetworkDeploymentActions
  #NetworkDeploymentActions: ['CREATE','UPDATE']

  # General settings
  TimeZone: 'America/Sao_Paulo'
  NtpServer:
    - 0.pool.ntp.org
  DnsServers:
    - 192.0.2.254

  ControlFixedIPs: [{'ip_address':'192.0.2.40'}]
  PublicVirtualFixedIPs: [{'ip_address':'10.0.0.40'}]
  InternalApiVirtualFixedIPs: [{'ip_address':'172.17.0.40'}]
  StorageVirtualFixedIPs: [{'ip_address':'172.19.0.40'}]
  StorageMgmtVirtualFixedIPs: [{'ip_address':'172.16.0.40'}]
  RedisVirtualFixedIPs: [{'ip_address':'172.17.0.39'}]

  ExternalNetValueSpecs: {'provider:physical_network': 'external_ful', 'provider:network_type': 'flat'}

  # OpenStack Neutron settings
  NeutronExternalNetworkBridge: "''"
  NeutronEnableIsolatedMetadata: true
  NeutronGlobalPhysnetMtu: 1500
  NeutronNetworkVLANRanges:
    - datacentre:100:120
  NeutronTunnelTypes: 'geneve'
  NeutronNetworkType: ['geneve','vlan']

  # Barbican
  #BarbicanSimpleCryptoGlobalDefault: true

  ControllerSchedulerHints:
    'capabilities:node': 'controller-%index%'
  ComputeSchedulerHints:
    'capabilities:node': 'compute-%index%'

  HostnameMap:
    fulldeploy-controller-0: controller-1
    fulldeploy-controller-1: controller-2
    fulldeploy-controller-2: controller-3
    fulldeploy-novacompute-0: compute-1
    fulldeploy-novacompute-1: compute-2
    fulldeploy-novacompute-2: compute-3

  ControlPlaneDefaultRoute: 192.0.2.254
  ControlPlaneSubnetCidr: '24'
  ExternalInterfaceDefaultRoute: 10.0.0.254

  ComputeExtraConfig:
    nova::compute::resume_guests_state_on_host_boot: true

